baseURL: "https://example.com"
languageCode: "en-us"
title: "Hugo Novela"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
